# Generated by Django 4.0.6 on 2022-07-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_review_ip_remove_review_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
    ]
